database:
  type: SQLITE # SQLITE / MYSQL / MONGODB
  sqlite:
    file: data.db
    connection-timeout-ms: 10000
  mysql:
    host: localhost
    port: 3306
    database: pncases
    username: root
    password: ""
    parameters: "useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    pool-size: 10
    connection-timeout-ms: 10000
  mongodb:
    uri: "mongodb://localhost:27017"
    database: pncases
    collection: pncases

case-files:
  auto-export: true

holograms:
  provider: AUTO # AUTO / FANCY / DECENT

reward-symbols:
  vault: "$"
  playerpoints: "✦"

keys:
  money_key:
    name: "§x§F§F§5§3§0§0Ключ с монетами"
  points_key:
    name: "§x§0§0§D§5§F§FКлюч с поинтами"
  items_key:
    name: "§x§0§0§9§8§F§FКлюч с ресурсами"
  donate_key:
    name: "§x§F§F§8§6§0§0Донат ключ"
