name: pnCases
version: '${version}'
main: ru.privatenull.pnCases
api-version: '1.19'
authors: [ privatenull ]
softdepend: [LuckPerms, FancyHolograms, DecentHolograms, Vault, PlayerPoints]
commands:
  pncases:
    description: dohcases admin commands
    usage: /pncases machine [case] | /pncases setcase <case> | /pncases delcase <case> | /pncases givekey <player> <key> <amount> | /pncases reload
    permission: pncases.admin
permissions:
  pncases.admin:
    default: op
